### ISSUE TITLE
U gate parsing from QASM to Q# is wrong

### ISSUE THREAD

**Issue by jond01** [qsharp-community/qsharp-integrations#12]
The following QASM code
```
OPENQASM 2.0;
qreg q[1];
U(θ,φ,λ) q[0];
```
is translated to this Q# code (not complete):
```
use q = Qubit[1] {
    Rx(θ, q[0]);
    Ry(φ, q[0]);
    Rz(λ, q[0]);
    ResetAll(q);
}
```
This logic is implemented in the following parts of `Parser.cs`:
https://github.com/qsharp-community/qsharp-integrations/blob/03fcaa26062d867975586c6f4d94b2d3f13983c3/src/OpenQasmReader/Parser.cs#L118-L121

https://github.com/qsharp-community/qsharp-integrations/blob/03fcaa26062d867975586c6f4d94b2d3f13983c3/src/OpenQasmReader/Parser.cs#L740-L778

However, the definition of [QASM's U gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) is:
![image](https://user-images.githubusercontent.com/36337649/126515360-408021b1-ec3d-4f89-a8b5-3cebc59a8109.png)

And the above is not equal to Rz(λ)*Ry(φ)*Rx(θ).
See the following gist for more details:
https://gist.github.com/jond01/c942a7358e27e99aa6a68ea7ef42fe65

The correct translation is:
U(θ, φ, λ) = e^{i(φ+λ)/2}*Rz(φ)*Ry(θ)*Rz(λ)
(See Eqs. (1) and (2) in https://arxiv.org/pdf/2104.14722.pdf#page=11.)

It is essential to fix `ParseUGate` code and would be nice to implement a Q# operation U that contains the rotations and the global phase.

**Comment by crazy4pi314** [comment]
@jond01 I haven't checked yet, but we have merged some possible fixes here, does this resolve this issue?

**Comment by jond01** [comment]
Yes, thanks :)
